image: golang:1.24

before_script:
  - apt-get update
  - apt-get install -y make curl git shellcheck
  - export GOTOOLCHAIN=local

stages:
- build
- test
- build-log
- documentation

make-all:
  stage: build
  script: make check

make-check:
  stage: test
  script: make check
  artifacts:
    when: always
    paths:
    - ./tests/test.*

make-check-386:
  stage: test
  script: GOARCH=386 make check
  artifacts:
    when: always
    paths:
    - ./tests/test.*

make-shellcheck:
  stage: test
  script: cd tests && make shellcheck

# Succeeds if no changes are suggested by gofmt -d .
gofmt:
  stage: test
  script: if gofmt -d . | grep . ; then false ; else true ; fi

codespell:
  image: debian:testing
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y codespell
  script:
    - codespell -L erro

go-vet:
  stage: test
  script: go vet ./...

go-mod-tidy:
  stage: test
  script: go mod tidy -diff

govulncheck:
  stage: test
  # v1.1.4 appears to be latest version supporting go 1.24
  script: go run golang.org/x/vuln/cmd/govulncheck@v1.1.4 -show verbose ./...

build-log-go:
  stage: build-log
  allow_failure: true
  # Doesn't need any of the artifacts from the test stage.
  dependencies: []
  script:
  - git clone https://git.glasklar.is/sigsum/core/log-go.git &&
    cd log-go && go work init && go work use . .. && go build ./...

make-doc:
  stage: documentation
  before_script:
    - apt-get update
    - apt-get install -y make git help2man pandoc mandoc man-db
  script:
    - make doc
    # https://manpages.debian.org/testing/mandoc/mandoc.1.en.html
    # https://lintian.debian.org/tags/bad-whatis-entry.html
    - MANPAGER=cat mandoc -T lint doc/*.? || true
    - MANPAGER=cat mandoc -T lint -W error doc/*.?
    - lexgrog --debug doc/*.1

.make-debian: &make-debian
  allow_failure: true
  stage: test
  before_script:
    - sed -i 's/ deb$/ deb deb-src/' /etc/apt/sources.list.d/*.sources
    - apt-get update
    - apt-get install -y --no-install-recommends git ca-certificates dctrl-tools dpkg-dev devscripts
  script:
    - git clone https://salsa.debian.org/go-team/packages/sigsum-go.git
    - mv sigsum-go/debian debian
    - rm -rf sigsum-go
    - rm -f debian/changelog
    - dch --create --package sigsum-go --newversion 0.0-1 "Build"
    - git archive --format=tar.gz HEAD > ../sigsum-go_0.0.orig.tar.gz
    - apt-get install -y --no-install-recommends build-essential $(cat debian/control | grep-dctrl -n -s Build-Depends . | sed -e 's/,//' -e  's/<.*>//' -e 's/(.*)//')
    - dpkg-buildpackage --no-sign
    - dpkg -c ../sigsum-go_0.0-1_amd64.deb
    - dpkg -I ../sigsum-go_0.0-1_amd64.deb

make-debian-forky:
  image: debian:forky-slim
  extends: .make-debian

make-debian-trixie:
  image: debian:trixie-slim
  extends: .make-debian
