TESTS = ssh-agent-test \
	sign-verify-test sign-agent-test sign-verify-ssh-test \
	sign-ssh-interop-test verify-ssh-interop-test keyhash-test \
	token-record-test token-create-raw-test token-create-header-test
all:

check:
	./run-tests $(TESTS)
