#! /bin/sh

set -e

./bin/sigsum-key generate -o test.key

echo foo > test.msg
rm -f test.msg.sig

ssh-agent sh <<EOF
set -e
# Add private key to agent, then delete.
ssh-add test.key 2>/dev/null
rm test.key

# Pass only public key to sigsum.
./bin/sigsum-key sign -n sigsum-test -k test.key.pub -o test.msg.sig < test.msg
EOF

./bin/sigsum-key verify -k test.key.pub -s test.msg.sig -n sigsum-test < test.msg
