#! /bin/sh

set -e

./bin/sigsum-key gen -o test.key

echo foo > test.msg
rm -f test.msg.sig

./bin/sigsum-key sign --ssh -k test.key --namespace sigsum-test -o test.msg.sig < test.msg
ssh-keygen -q -Y check-novalidate -f test.key.pub -n sigsum-test -s test.msg.sig < test.msg
