#! /bin/sh

set -e

./bin/sigsum-key gen -o test.log.key
./bin/sigsum-key gen -o test.submit.key

# Start sigsum log server
rm -f test.log.sth
echo "startup=empty" > test.log.sth.startup
./bin/sigsum-log-primary --key test.log.key \
    --interval=1s --log-level=error --ephemeral-test-backend --sth-path test.log.sth &

SIGSUM_PID=$!

cleanup () {
    kill ${SIGSUM_PID}
}

trap cleanup EXIT

for x in $(seq 5); do
    echo >&2 "submit $x"
    # Must be exactly 32 bytes
    printf "%31s\n" foo-$x \
	| ./bin/sigsum-log -o test.$x.proof -k test.submit.key --log-url http://localhost:6965 --log-key test.log.key.pub
done

for x in $(seq 5); do
    echo >&2 "verify $x"
    printf "%31s\n" foo-$x \
	| ./bin/sigsum-verify --submit-key test.submit.key.pub --log-key test.log.key.pub "test.$x.proof"
done

# Check that the message is taken into account in validation.
if printf "%31s\n" foo-2 \
	| ./bin/sigsum-verify --submit-key test.submit.key.pub --log-key test.log.key.pub "test.1.proof" ; then
    false
else
    true
fi
