#! /bin/sh

set -e

./bin/sigsum-key gen -o test.log.key
./bin/sigsum-key gen -o test.submit.key

# Start sigsum log server
rm -f test.log.sth
echo "startup=empty" > test.log.sth.startup
./bin/sigsum-log-primary --key test.log.key \
    --interval=1s --log-level=error --ephemeral-test-backend --sth-path test.log.sth &

SIGSUM_PID=$!

cleanup () {
    kill ${SIGSUM_PID}
}

trap cleanup EXIT

# Give log server some time to get ready.
sleep 2

echo "log $(./bin/sigsum-key hex -k test.log.key.pub) http://localhost:6965" > test.policy
echo "quorum none" >> test.policy

for x in $(seq 5); do
    echo >&2 "submit $x"
    # Must be exactly 32 bytes
    printf "%31s\n" foo-$x \
	| ./bin/sigsum-log --diagnostics=warning --raw-hash -o test.$x.proof -k test.submit.key --policy test.policy
done

for x in $(seq 5); do
    echo >&2 "verify $x"
    printf "%31s\n" foo-$x \
	| ./bin/sigsum-verify --raw-hash --submit-key test.submit.key.pub --policy test.policy "test.$x.proof"
done

# Check that the message is taken into account in validation.
if printf "%31s\n" foo-2 \
	| ./bin/sigsum-verify --submit-key test.submit.key.pub --policy test.policy "test.1.proof" ; then
    false
else
    true
fi
