#! /bin/sh

set -e

./bin/sigsum-key gen -o test.log.key
./bin/sigsum-key gen -o test.submit.key

# Start sigsum log server
rm -f test.log.sth
echo "startup=empty" > test.log.sth.startup
./bin/sigsum-log-primary --key test.log.key \
    --interval=3s --log-level=error --ephemeral-test-backend --sth-path test.log.sth &

SIGSUM_PID=$!

cleanup () {
    kill ${SIGSUM_PID}
}

trap cleanup EXIT

for x in $(seq 5); do
    echo >&2 "submit $x"
    # Must be exactly 32 bytes
    printf "%31s\n" foo-$x \
	| ./bin/sigsum-log -o /dev/null -k test.submit.key --log-url http://localhost:6965 --log-key test.log.key.pub
done
