#! /bin/sh

set -e

# This test was created by starting from sigsum-submit-witness-test and adding a litewitness process there

# This test expects sigsum-agent to be already running using the socket given by AGENT_SOCKET below
AGENT_SOCKET=/tmp/agent-sock

# Remove any old litewitness things
rm -rf tmp-litewitness

# Build litewitness and witnessctl
mkdir tmp-litewitness
cd tmp-litewitness
git clone https://git.glasklar.is/elias/torchwood.git
cd torchwood/cmd/litewitness
go build
cd ../witnessctl
go build
cd ../../../..

./bin/sigsum-key generate -o test.log.key
./bin/sigsum-key generate -o test.submit.key
./bin/sigsum-key generate -o test.witness.key

# Add log key to litewitness
tmp-litewitness/torchwood/cmd/witnessctl/witnessctl add-sigsum-log -db tmp-litewitness/litewitness.db -key $(cat test.log.key.pub | ./bin/sigsum-key to-hex)

# Check that agent is available and get witness pubkey
echo Checking that agent socket $AGENT_SOCKET exists
ls $AGENT_SOCKET
LITEWITNESS_PUBKEY_AS_HEX=$(SSH_AUTH_SOCK=$AGENT_SOCKET ssh-add -L | ./bin/sigsum-key to-hex)
LITEWITNESS_KEYHASH=$(SSH_AUTH_SOCK=$AGENT_SOCKET ssh-add -L | ./bin/sigsum-key to-hash)
echo LITEWITNESS_PUBKEY_AS_HEX = $LITEWITNESS_PUBKEY_AS_HEX
echo LITEWITNESS_KEYHASH = $LITEWITNESS_KEYHASH

# Prepare policy file
echo "log $(./bin/sigsum-key to-hex -k test.log.key.pub) http://localhost:6965" > test.policy
echo "witness W1 $(./bin/sigsum-key to-hex -k test.witness.key.pub) http://localhost:7777" >> test.policy
echo "witness W2 $LITEWITNESS_PUBKEY_AS_HEX http://localhost:9999" >> test.policy
echo "group quorum-rule 2 W1 W2" >> test.policy
echo "quorum quorum-rule" >> test.policy

echo Policy file test.policy looks like this:
cat test.policy

# Start witness server
rm -f test.witness.cth
./bin/sigsum-witness -k test.witness.key --log-key test.log.key.pub \
  --state-file test.witness.cth localhost:7777 &

WITNESS_PID=$!

# Start litewitness server
tmp-litewitness/torchwood/cmd/litewitness/litewitness -db tmp-litewitness/litewitness.db -ssh-agent $AGENT_SOCKET -key $LITEWITNESS_KEYHASH -listen localhost:9999 -name litewitness-test &

LITEWITNESS_PID=$!

# Start sigsum log server
rm -f test.log.sth
echo "startup=empty" > test.log.sth.startup
./bin/sigsum-log-primary --key-file test.log.key \
    --policy-file=test.policy \
    --interval=1s --log-level=error --backend=ephemeral --sth-file test.log.sth &

SIGSUM_PID=$!

cleanup () {
    kill ${SIGSUM_PID} ${WITNESS_PID} ${LITEWITNESS_PID}
}

trap cleanup EXIT

# Give log server some time to get ready.
sleep 2

for x in $(seq 5); do
    echo >&2 "submit $x"
    # Must be exactly 32 bytes
    printf "%31s\n" "foo-$x" \
	| ./bin/sigsum-submit --diagnostics=warning --raw-hash -o "test.$x.proof" -k test.submit.key --policy test.policy
done

for x in $(seq 5); do
    echo >&2 "verify $x"
    printf "%31s\n" "foo-$x" \
	| ./bin/sigsum-verify --raw-hash --key test.submit.key.pub --policy test.policy "test.$x.proof"
done
