#! /bin/sh

set -e

./bin/sigsum-key gen -o test.key

ssh-agent sh <<EOF
set -e
# Add private key to agent, then delete.
ssh-add test.key 2>/dev/null
rm test.key

go run ./use-agent < test.key.pub
<<EOF
