#! /bin/sh

set -e

./sigsum-key gen -o test.key
./sigsum-key gen -o test.log.key

./sigsum-token create -k test.key --log test.log.key.pub -o test.token
./sigsum-token verify --log test.log.key.pub -k test.key.pub < test.token
# Check that validation fails when log key is changed.
if ./sigsum-token verify --log test.key.pub -k test.key.pub < test.token 2>/dev/null; then
    exit 1
fi
