#! /bin/sh

set -e

rm -f test.key test.key.pub
ssh-keygen -q -N '' -t ed25519 -f test.key

echo foo > test.msg
rm -f test.msg.sig

ssh-keygen -O hashalg=sha256 -q -Y sign -f test.key -n sigsum-test test.msg
if sed '/^-/d' < test.msg.sig |base64 -d | strings | grep sha256 >/dev/null ; then
    # Got the expected hash algorithm
    true
else
    echo "ssh-keygen appears to be too old, openssh 8.9 or later is needed"
    exit 77
fi
./bin/sigsum-key verify -k test.key.pub -s test.msg.sig --namespace sigsum-test < test.msg

# Check that modified message makes verification fail.
if (cat test.msg && echo) \
    | ./sigsum-key verify -k test.key.pub -s test.msg.sig --namespace sigsum-test 2>/dev/null ; then
    false
else
    true
fi
