#!/bin/bash

set -eu
cd "$(dirname "$0")"

opt=$1; shift
case "$opt" in
	--help)
		../../../build/sigsum-verify --help | sed "/^Usage:/ a\\\nOptions:"
		;;
	--version)
		../../../build/sigsum-verify --version
		;;
	*)
		echo "invalid option: $opt"
		exit 1
		;;
esac
